apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: nodejs-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/michealjack1/nodejs-tekton-openshift-1
